"""order table fields added shipping address,city,pincode

Revision ID: 4d26de4468fd
Revises: dbd54bee639d
Create Date: 2024-03-09 17:44:54.693128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d26de4468fd'
down_revision = 'dbd54bee639d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cus_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ord_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pincode')
        batch_op.drop_column('ord_city')
        batch_op.drop_column('cus_name')

    # ### end Alembic commands ###
