"""order table fields added shipping address not added so added that field

Revision ID: 7485da9b3e5b
Revises: 4d26de4468fd
Create Date: 2024-03-09 17:47:34.804928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7485da9b3e5b'
down_revision = '4d26de4468fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
