"""order table telephone field added 

Revision ID: f392849fe6f5
Revises: 9e8d59824897
Create Date: 2024-03-11 18:20:50.529884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f392849fe6f5'
down_revision = '9e8d59824897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
